# fly.toml file generated for relaycloud on 2022-06-26T11:34:16-04:00

app = "relaycloud"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 4000
processes = ["app"]
protocol = "tcp"
script_checks = []
tcp_checks = []
http_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
